kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portal-rolebinding
  labels:
    app: tools-rbac
subjects:
  - kind: ServiceAccount
    name: {{ .Values.setting.sa }}
    apiGroup: ""
    namespace: {{ .Values.setting.namespace }}
roleRef:
  kind: ClusterRole
  name: portal-read
  apiGroup: rbac.authorization.k8s.io

